PROGS = ch3-1	ch3-5	ch3-10	ch3-11	ch3-13
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch3-1:
	g++	-o	ch3-1	ch3-1.cpp	-Wall
ch3-5:
	g++	-o	ch3-5	ch3-5.cpp	-Wall
ch3-10:
	g++	-o	ch3-10	ch3-10.cpp	-Wall
ch3-11:
	g++	-o	ch3-11	ch3-11.cpp	-Wall
ch3-13:
	g++	-o	ch3-13	ch3-13.cpp	-Wall