PROGS = ch10-1	ch10-3	ch10-4	ch10-8
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch10-1:
	g++	-o	ch10-1	ch10-1.cpp	-Wall
ch10-3:
	g++	-o	ch10-3	ch10-3.cpp	-Wall
ch10-4:
	g++	-o	ch10-4	ch10-4.cpp	-Wall
ch10-8:
	g++	-o	ch10-8	ch10-8.cpp	-Wall
