PROGS = ch2-2	ch2-4	ch2-7	ch2-8
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch2-2:
	g++	-o	ch2-2	ch2-2.cpp	-Wall
ch2-4:
	g++	-o	ch2-4	ch2-4.cpp	-Wall
ch2-7:
	g++	-o	ch2-7	ch2-7.cpp	-Wall
ch2-8:
	g++	-o	ch2-8	ch2-8.cpp	-Wall