target:sig_speed_sigsuspend	sig_speed_sigsuspend_modify
sig_speed_suspend:
	gcc -o sig_speed_sigsuspend sig_speed_sigsuspend.c
sig_speed_suspend_modify:
	gcc -o sig_speed_sigsuspend_modify sig_speed_sigsuspend_modify.c