PROGS = ch6-1	ch6-7	ch6-10	ch6-12
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch6-1:
	g++	-o	ch6-1	ch6-1.cpp	-Wall
ch6-7:
	g++	-o	ch6-7	ch6-7.cpp	-Wall
ch6-10:
	g++	-o	ch6-10	ch6-10.cpp	-Wall
ch6-12:
	g++	-o	ch6-12	ch6-12.cpp	-Wall