all : getcwd hostinfo mycat pipe_ls time
getcwd : getcwd.o
	gcc -o getcwd getcwd.o 
getcwd.o : getcwd.c
	gcc -c getcwd.c
hostinfo : hostinfo.o
	gcc -o hostinfo hostinfo.o 
hostinfo.o : hostinfo.c
	gcc -c hostinfo.c
mycat : mycat.o
	gcc -o mycat mycat.o 
mycat.o : mycat.c
	gcc -c mycat.c
pipe_ls : pipe_ls.o
	gcc -o pipe_ls pipe_ls.o 
pipe_ls.o : pipe_ls.c
	gcc -c pipe_ls.c
time : time.o
	gcc -o time time.o 
time.o : time.c
	gcc -c time.c



 
