PROGS = ch1-6	ch1-8	ch1-13
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch1-6:
	g++	-o	ch1-6	ch1-6.cpp	-Wall
ch1-8:
	g++	-o	ch1-8	ch1-8.cpp	-Wall
ch1-13:
	g++	-o	ch1-13	ch1-13.cpp	-Wall