PROGS = ch12-2	ch12-3	ch12-5
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch12-2:
	g++	-o	ch12-2	ch12-2.cpp	-Wall
ch12-3:
	g++	-o	ch12-3	ch12-3.cpp	-Wall
ch12-5:
	g++	-o	ch12-5	ch12-5.cpp	-Wall