PROGS = ch8-1	ch8-4	ch8-5	ch8-8	ch8-9
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch8-1:
	g++	-o	ch8-1	ch8-1.cpp	-Wall
ch8-4:
	g++	-o	ch8-4	ch8-4.cpp	-Wall
ch8-5:
	g++	-o	ch8-5	ch8-5.cpp	-Wall
ch8-8:
	g++	-o	ch8-8	ch8-8.cpp	-Wall
ch8-9:
	g++	-o	ch8-9	ch8-9.cpp	-Wall