target:svshm_xfr_reader	svshm_xfr_writer	svshm_xfr_thread
svshm_xfr_reader:
	gcc -o svshm_xfr_reader svshm_xfr_reader.c
svshm_xfr_writer:
	gcc -o svshm_xfr_writer svshm_xfr_writer.c
svshm_xfr_thread:
	gcc -o svshm_xfr_thread svshm_xfr_thread.c -lpthread -lrt