PROGS = ch4-3	ch4-7	ch4-8	ch4-9	ch4-14	ch4-17
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch4-3:
	g++	-o	ch4-3	ch4-3.cpp	-Wall
ch4-7:
	g++	-o	ch4-7	ch4-7.cpp	-Wall
ch4-8:
	g++	-o	ch4-8	ch4-8.cpp	-Wall
ch4-9:
	g++	-o	ch4-9	ch4-9.cpp	-Wall
ch4-14:
	g++	-o	ch4-14	ch4-14.cpp	-Wall
ch4-17:
	g++	-o	ch4-17	ch4-17.cpp	-Wall