PROGS = ch9-2	ch9-4	ch9-6	ch9-10
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch9-2:
	g++	-o	ch9-2	ch9-2.cpp	-Wall
ch9-4:
	g++	-o	ch9-4	ch9-4.cpp	-Wall
ch9-6:
	g++	-o	ch9-6	ch9-6.cpp	-Wall
ch9-10:
	g++	-o	ch9-10	ch9-10.cpp	-Wall