PROGS = ch7-1	ch7-5	ch7-6	ch7-8	ch7-11
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch7-1:
	g++	-o	ch7-1	ch7-1.cpp	-Wall
ch7-5:
	g++	-o	ch7-5	ch7-5.cpp	-Wall
ch7-6:
	g++	-o	ch7-6	ch7-6.cpp	-Wall
ch7-8:
	g++	-o	ch7-8	ch7-8.cpp	-Wall
ch7-11:
	g++	-o	ch7-11	ch7-11.cpp	-Wall