PROGS = ch5-4	ch5-8	ch5-10	ch5-14	ch5-17
target : clean	$(PROGS)
.PHONY	:clean
clean :
	rm -f *.o $(PROGS)
ch5-4:
	g++	-o	ch5-4	ch5-4.cpp	-Wall
ch5-8:
	g++	-o	ch5-8	ch5-8.cpp	-Wall
ch5-10:
	g++	-o	ch5-10	ch5-10.cpp	-Wall
ch5-14:
	g++	-o	ch5-14	ch5-14.cpp	-Wall
ch5-17:
	g++	-o	ch5-17	ch5-17.cpp	-Wall